services:

  matchmaking-db:
    image: postgres:latest
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - micro-net

  flyway:
    image: flyway/flyway
    environment:
      FLYWAY_URL: jdbc:postgresql://matchmaking-db:5432/matches_db
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
      FLYWAY_BASELINE_ON_MIGRATE: true
    volumes:
      - ./python-db-migrations:/flyway/sql
    depends_on:
      - matchmaking-db
    networks:
      - micro-net

  venue-db:
    image: postgres:latest
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./venue-service/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - micro-net

  auth-db:
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./Authentication-Service/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - micro-net

  eureka:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - micro-net

  api-gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - eureka
    networks:
      - micro-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - micro-net

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - micro-net


  player-db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
        POSTGRES_USERNAME: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - ./player-service/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - micro-net

  authentication-service:
    build:
      context: .
      dockerfile: Authentication-Service/Dockerfile
    ports:
      - "8082"
    depends_on:
      - auth-db
      - eureka
    networks:
      - micro-net
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/user_auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  player-service:
    build:
      context: .
      dockerfile: player-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - player-db
      - eureka
      - kafka
    networks:
      - micro-net
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://player-db:5432/player_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  venue-service:
    build:
      context: .
      dockerfile: venue-service/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - venue-db
      - eureka
    networks:
      - micro-net
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://venue-db:5432/venue_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  match-making-service:
    build:
      context: ./match-making
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./match-making:/app
    depends_on:
      - matchmaking-db
    networks:
      - micro-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://matchmaking-db:5432/matchmaking-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

networks:
  micro-net:
    driver: bridge