spring:
 cloud:
   gateway:
     routes:
       - id: player-service
         uri: lb://PLAYER-SERVICE
         predicates:
           - Path=/api/v1/player/**
         filters:
           - AuthenticationFilter

       - id: authentication-service
         uri: lb://AUTHENTICATION-SERVICE
         predicates:
           - Path=/auth/**
       - id: venue-service
         uri: lb://VENUE-SERVICE
         predicates:
           - Path=/api/v1/venue/**
         filters:
           - AuthenticationFilter
       - id: match-making-service
         uri: http://match-making-service:5000
         predicates:
           - Path=/api/v1/match/**
         filters:
           - AuthenticationFilter

       - id: chat-service-rest
         uri: lb://CHAT-SERVICE
         predicates:
           - Path=/api/v1/chat/**
         filters:
           - AuthenticationFilter

       - id: chat-service-websocket
         uri: ws://chat-service:8090
         predicates:
           - Path=/ws/**

 application:
   name: api-gateway

eureka:
  client:
    service-url:
      defaultZone : http://eureka:8761/eureka/


