spring:
 cloud:
   gateway:
     routes:
       - id: player-service
         uri: lb://PLAYER-SERVICE
         predicates:
           - Path=/api/v1/player/**
         filters:
           - AuthenticationFilter

       - id: authentication-service
         uri: lb://AUTHENTICATION-SERVICE
         predicates:
           - Path=/auth/**
       - id: venue-service
         uri: lb://VENUE-SERVICE
         predicates:
           - Path=/api/v1/venue/**
         filters:
           - AuthenticationFilter

 application:
   name: api-gateway

eureka:
  client:
    service-url:
      defaultZone : http://eureka:8761/eureka/


